apiVersion: v1 
kind: Namespace
metadata:
  name: sales-system 
---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: sales-pod # base Pod name
  namespace: sales-system 
spec:
  selector:
    matchLabels:
      app: sales 
  template:
    metadata:
      labels:
        app: sales # Selector for Pod name search.
    spec:
      dnsPolicy: ClusterFirstWithHostNet 
      hostNetwork: true 
      terminationGracePeriodSeconds: 60
      containers:
        # sales-api container configuration
      - name: sales-api 
        # gets patched to the specific docker image name in kind/sales-pod/kustomization.yaml
        # done to avoid hardcoding image name and version
        image: sales-api-image
        ports:
        - name: sales-api 
          containerPort: 3000 
        - name: sales-api-debug 
          containerPort: 4000
---
apiVersion: v1 
kind: Service 
metadata:
  name: sales-service 
  namespace: sales-system
spec:
  type: ClusterIP
  selector:
    app: sales 
  ports:
  - name: sales-api 
    port: 3000
    targetPort: sales-api 
  - name: sales-api-debug 
    port: 4000 
    targetPort: sales-api-debug 
    