apiVersion: v1 
kind: Namespace
metadata:
  name: sales-system 
---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: sales-pod # base Pod name
  namespace: sales-system 
spec:
  selector:
    matchLabels:
      app: sales 
  template:
    metadata:
      labels:
        app: sales # Selector for Pod name search.
    spec:
      dnsPolicy: ClusterFirstWithHostNet 
      hostNetwork: true 
      terminationGracePeriodSeconds: 60
      containers:
        # sales-api container configuration
      - name: sales-api 
        # gets patched to the specific docker image name in kind/sales-pod/kustomization.yaml
        # done to avoid hardcoding image name and version
        image: sales-api-image
        ports:
        - name: sales-api 
          containerPort: 3000 
        - name: sales-api-debug 
          containerPort: 4000
<<<<<<< HEAD
        readinessProbe: # readiness probes mark the service available to accept traffic
          httpGet:
            path: /debug/readiness 
            port: 4000
          initialDelaySeconds: 15 
          periodSeconds: 15 
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
          httpGet:
            path: /debug/liveness 
            port: 4000
          initialDelaySeconds: 30 
          periodSeconds: 30 
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        env:
        - name: KUBERNETES_NAMESPACE 
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_PODNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name 
        - name: KUBERNETES_NAMESPACE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName 
=======
>>>>>>> set up debugging support for use during development
---
apiVersion: v1 
kind: Service 
metadata:
  name: sales-service 
  namespace: sales-system
spec:
  type: ClusterIP
  selector:
    app: sales 
  ports:
  - name: sales-api 
    port: 3000
<<<<<<< HEAD
    targetPort: sales-api 
=======
>>>>>>> set up debugging support for use during development
  - name: sales-api-debug 
    port: 4000 
    targetPort: sales-api-debug 
    