kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane 
  extraPortMappings:
  - containerPort: 3000
    hostPort: 3000 
  - containerPort: 4000 
<<<<<<< HEAD
    hostPort: 4000
  - containerPort: 5432
    hostPort: 5432
=======
    hostPort: 4000
>>>>>>> set up debugging support for use during development
